package cn.net.polyglot.config

const val MESSAGE = "message"
const val SEARCH = "search"
const val FRIEND = "friend"
const val MESSAGES = "messages"
const val FRIENDS = "friends"
const val USER = "user"
const val REQUEST = "request"
const val RESPONSE = "response"
const val DELETE = "delete"
const val LOGIN = "login"
const val REGISTER = "register"
const val TYPE = "type"
const val SUBTYPE = "subtype"
const val VERSION = "version"
const val FROM = "from"
const val TO = "to"
const val INFO = "info"
const val NICKNAME = "nickname"
const val ID = "id"
const val PASSWORD = "password"
const val DIR = "dir"
const val HOST = "host"
const val BODY = "body"
const val ACCEPT = "accept"
const val TEXT = "text"
const val TCP_PORT = "tcp-port"
const val HTTP_PORT = "http-port"
const val KEYWORD = "keyword"
const val LEFT = "left"

const val END = "\r\n"
