package cn.net.polyglot.config

const val MESSAGE = "message"
const val SEARCH = "search"
const val FRIEND = "friend"
const val USER = "user"
const val REQUEST = "request"
const val RESPONSE = "response"
const val DELETE = "delete"
const val LIST = "list"
const val LOGIN = "login"
const val REGISTER = "register"
const val TYPE = "type"
const val SUBTYPE = "subtype"
const val VERSION = "version"
const val FROM = "from"
const val TO = "to"
const val INFO = "info"
const val NICKNAME = "nickname"
